# Generated by Django 3.2.5 on 2022-06-23 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'permissions': (('Personne_voir', 'Paco: voir'), ('Personne_voir_inactif', 'Paco: voir inactif'), ('Personne_voir_details', 'Paco: voir details'), ('Personne_ajouter', 'Paco: ajouter'), ('Personne_modifier', 'Paco: modifier'), ('Personne_activer', 'Paco: activer'), ('Personne_desactiver', 'Paco: desactiver'), ('Personne_supprimer', 'Paco: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Station_lieu_de_travail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'permissions': (('Station_lieu_de_travail_voir', 'Paco: voir'), ('Station_lieu_de_travail_voir_inactif', 'Paco: voir inactif'), ('Station_lieu_de_travail_voir_details', 'Paco: voir details'), ('Station_lieu_de_travail_ajouter', 'Paco: ajouter'), ('Station_lieu_de_travail_modifier', 'Paco: modifier'), ('Station_lieu_de_travail_activer', 'Paco: activer'), ('Station_lieu_de_travail_desactiver', 'Paco: desactiver'), ('Station_lieu_de_travail_supprimer', 'Paco: supprimer')),
            },
        ),
    ]
