# Generated by Django 3.2.5 on 2022-06-24 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satfd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu_de_travail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254, null=True, unique=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'permissions': (('Station_lieu_de_travail_voir', 'Paco: voir'), ('Station_lieu_de_travail_voir_inactif', 'Paco: voir inactif'), ('Station_lieu_de_travail_voir_details', 'Paco: voir details'), ('Station_lieu_de_travail_ajouter', 'Paco: ajouter'), ('Station_lieu_de_travail_modifier', 'Paco: modifier'), ('Station_lieu_de_travail_activer', 'Paco: activer'), ('Station_lieu_de_travail_desactiver', 'Paco: desactiver'), ('Station_lieu_de_travail_supprimer', 'Paco: supprimer')),
            },
        ),
        migrations.DeleteModel(
            name='Station_lieu_de_travail',
        ),
        migrations.AddField(
            model_name='personne',
            name='Prenom',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='adresse',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='conjoint',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='CIN/NIF du/de la conjoint(e)'),
        ),
        migrations.AddField(
            model_name='personne',
            name='gilet_couleur',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Couleur de Gilet'),
        ),
        migrations.AddField(
            model_name='personne',
            name='id_number',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='CIN/NIF'),
        ),
        migrations.AddField(
            model_name='personne',
            name='id_plaque',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Numéro de plaques'),
        ),
        migrations.AddField(
            model_name='personne',
            name='mere_cin_nif',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='CIN/NIF de la mère'),
        ),
        migrations.AddField(
            model_name='personne',
            name='naissance',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='pere_cin_nif',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='CIN/NIF du père'),
        ),
        migrations.AddField(
            model_name='personne',
            name='telephone',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='personne',
            name='lieu_de_travail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.lieu_de_travail'),
        ),
    ]
