# Generated by Django 3.2.5 on 2022-06-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satfd', '0002_auto_20220624_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='Prenom',
            new_name='prenom',
        ),
    ]
