# Generated by Django 3.2.5 on 2022-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satfd', '0003_rename_prenom_personne_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='email',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
