# Generated by Django 3.2.5 on 2022-06-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satfd', '0006_auto_20220625_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='conjoint',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='NIU du/de la conjoint(e)'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='id_number',
            field=models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='NIU'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='mere_cin_nif',
            field=models.CharField(default='', max_length=254, null=True, verbose_name='NIU de la mère'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='pere_cin_nif',
            field=models.CharField(default='', max_length=254, null=True, verbose_name='NIU du père'),
        ),
    ]
