# Generated by Django 3.2.5 on 2022-07-03 23:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('satfd', '0007_auto_20220625_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=254, null=True)),
                ('nom', models.CharField(max_length=254, null=True)),
                ('naissance', models.DateField(blank=True, default=datetime.datetime.now)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50, null=True, verbose_name='Sexe')),
                ('adresse', models.CharField(max_length=254, null=True)),
                ('telephone', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Numéro de téléphone')),
                ('email', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('id_number', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='NIU')),
                ('salaire', models.FloatField(null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Employe_voir', 'SATFD: voir'), ('Employe_voir_inactif', 'SATFD: voir inactif'), ('Employe_voir_details', 'SATFD: voir details'), ('Employe_ajouter', 'SATFD: ajouter'), ('Employe_modifier', 'SATFD: modifier'), ('Employe_activer', 'SATFD: activer'), ('Employe_desactiver', 'SATFD: desactiver'), ('Employe_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Employe_mortuaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=254, null=True)),
                ('nom', models.CharField(max_length=254, null=True)),
                ('naissance', models.DateField(blank=True, default=datetime.datetime.now)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50, null=True, verbose_name='Sexe')),
                ('adresse', models.CharField(max_length=254, null=True)),
                ('telephone', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Numéro de téléphone')),
                ('email', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('id_number', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='NIU')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Employe_mortuaire_voir', 'SATFD: voir'), ('Employe_mortuaire_voir_inactif', 'SATFD: voir inactif'), ('Employe_mortuaire_voir_details', 'SATFD: voir details'), ('Employe_mortuaire_ajouter', 'SATFD: ajouter'), ('Employe_mortuaire_modifier', 'SATFD: modifier'), ('Employe_mortuaire_activer', 'SATFD: activer'), ('Employe_mortuaire_desactiver', 'SATFD: desactiver'), ('Employe_mortuaire_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254, null=True, unique=True)),
                ('adresse', models.CharField(max_length=254, null=True, unique=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Hopital_voir', 'SATFD: voir'), ('Hopital_voir_inactif', 'SATFD: voir inactif'), ('Hopital_voir_details', 'SATFD: voir details'), ('Hopital_ajouter', 'SATFD: ajouter'), ('Hopital_modifier', 'SATFD: modifier'), ('Hopital_activer', 'SATFD: activer'), ('Hopital_desactiver', 'SATFD: desactiver'), ('Hopital_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Morgue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254, null=True, unique=True)),
                ('adresse', models.CharField(max_length=254, null=True, unique=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Morgue_voir', 'SATFD: voir'), ('Morgue_voir_inactif', 'SATFD: voir inactif'), ('Morgue_voir_details', 'SATFD: voir details'), ('Morgue_ajouter', 'SATFD: ajouter'), ('Morgue_modifier', 'SATFD: modifier'), ('Morgue_activer', 'SATFD: activer'), ('Morgue_desactiver', 'SATFD: desactiver'), ('Morgue_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Src_mone_ext',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254, null=True, unique=True)),
                ('adresse', models.CharField(max_length=254, null=True, unique=True)),
                ('remarque', models.CharField(max_length=254, null=True, unique=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Src_mone_ext_voir', 'SATFD: voir'), ('Src_mone_ext_voir_inactif', 'SATFD: voir inactif'), ('Src_mone_ext_voir_details', 'SATFD: voir details'), ('Src_mone_ext_ajouter', 'SATFD: ajouter'), ('Src_mone_ext_modifier', 'SATFD: modifier'), ('Src_mone_ext_activer', 'SATFD: activer'), ('Src_mone_ext_desactiver', 'SATFD: desactiver'), ('Src_mone_ext_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Surcursale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254, null=True, unique=True)),
                ('adresse', models.CharField(max_length=254, null=True, unique=True)),
                ('montant_caisse', models.FloatField(null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Surcursale_voir', 'SATFD: voir'), ('Surcursale_voir_inactif', 'SATFD: voir inactif'), ('Surcursale_voir_details', 'SATFD: voir details'), ('Surcursale_ajouter', 'SATFD: ajouter'), ('Surcursale_modifier', 'SATFD: modifier'), ('Surcursale_activer', 'SATFD: activer'), ('Surcursale_desactiver', 'SATFD: desactiver'), ('Surcursale_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.AlterModelOptions(
            name='gilet_couleur',
            options={'ordering': ('date_created',), 'permissions': (('Gilet_couleur_voir', 'SATFD: voir'), ('Gilet_couleur_voir_inactif', 'SATFD: voir inactif'), ('Gilet_couleur_voir_details', 'SATFD: voir details'), ('Gilet_couleur_ajouter', 'SATFD: ajouter'), ('Gilet_couleur_modifier', 'SATFD: modifier'), ('Gilet_couleur_activer', 'SATFD: activer'), ('Gilet_couleur_desactiver', 'SATFD: desactiver'), ('Gilet_couleur_supprimer', 'SATFD: supprimer'))},
        ),
        migrations.AlterModelOptions(
            name='lieu_de_travail',
            options={'ordering': ('date_created',), 'permissions': (('Station_lieu_de_travail_voir', 'SATFD: voir'), ('Station_lieu_de_travail_voir_inactif', 'SATFD: voir inactif'), ('Station_lieu_de_travail_voir_details', 'SATFD: voir details'), ('Station_lieu_de_travail_ajouter', 'SATFD: ajouter'), ('Station_lieu_de_travail_modifier', 'SATFD: modifier'), ('Station_lieu_de_travail_activer', 'SATFD: activer'), ('Station_lieu_de_travail_desactiver', 'SATFD: desactiver'), ('Station_lieu_de_travail_supprimer', 'SATFD: supprimer'))},
        ),
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ('date_created',), 'permissions': (('Personne_voir', 'SATFD: voir'), ('Personne_voir_inactif', 'SATFD: voir inactif'), ('Personne_voir_details', 'SATFD: voir details'), ('Personne_ajouter', 'SATFD: ajouter'), ('Personne_modifier', 'SATFD: modifier'), ('Personne_activer', 'SATFD: activer'), ('Personne_desactiver', 'SATFD: desactiver'), ('Personne_supprimer', 'SATFD: supprimer'))},
        ),
        migrations.AddField(
            model_name='personne',
            name='statut',
            field=models.CharField(choices=[('Vivant', 'Vivant'), ('Malade', 'Malade'), ('Mort', 'Mort')], max_length=50, null=True, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='personne',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rapport_deces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('employé', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.employe_mortuaire')),
                ('personne_inscrite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.personne')),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Rapport_deces_voir', 'SATFD: voir'), ('Rapport_deces_voir_inactif', 'SATFD: voir inactif'), ('Rapport_deces_voir_details', 'SATFD: voir details'), ('Rapport_deces_ajouter', 'SATFD: ajouter'), ('Rapport_deces_modifier', 'SATFD: modifier'), ('Rapport_deces_activer', 'SATFD: activer'), ('Rapport_deces_desactiver', 'SATFD: desactiver'), ('Rapport_deces_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Prets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('employé', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.employe')),
                ('personne_inscrite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.personne')),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Prets_voir', 'SATFD: voir'), ('Prets_voir_inactif', 'SATFD: voir inactif'), ('Prets_voir_details', 'SATFD: voir details'), ('Prets_ajouter', 'SATFD: ajouter'), ('Prets_modifier', 'SATFD: modifier'), ('Prets_activer', 'SATFD: activer'), ('Prets_desactiver', 'SATFD: desactiver'), ('Prets_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Paiements_hebdo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('employé', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.employe')),
                ('personne_inscrite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.personne')),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Paiements_hebdo_voir', 'SATFD: voir'), ('Paiements_hebdo_voir_inactif', 'SATFD: voir inactif'), ('Paiements_hebdovoir_details', 'SATFD: voir details'), ('Paiements_hebdo_ajouter', 'SATFD: ajouter'), ('Paiements_hebdo_modifier', 'SATFD: modifier'), ('Paiements_hebdo_activer', 'SATFD: activer'), ('Paiements_hebdo_desactiver', 'SATFD: desactiver'), ('Paiements_hebdo_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Paiements_dettes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('employé', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.employe')),
                ('personne_inscrite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.personne')),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Paiements_dettes_voir', 'SATFD: voir'), ('Paiements_dettes_voir_inactif', 'SATFD: voir inactif'), ('Paiements_dettes_voir_details', 'SATFD: voir details'), ('Paiements_dettes_ajouter', 'SATFD: ajouter'), ('Paiements_dettes_modifier', 'SATFD: modifier'), ('Paiements_dettes_activer', 'SATFD: activer'), ('Paiements_dettes_desactiver', 'SATFD: desactiver'), ('Paiements_dettes_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=254, null=True)),
                ('nom', models.CharField(max_length=254, null=True)),
                ('naissance', models.DateField(blank=True, default=datetime.datetime.now)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50, null=True, verbose_name='Sexe')),
                ('adresse', models.CharField(max_length=254, null=True)),
                ('telephone', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Numéro de téléphone')),
                ('email', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('id_number', models.CharField(default='', max_length=254, null=True, unique=True, verbose_name='NIU')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('hopital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.hopital')),
                ('utilisateur', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Medecin_voir', 'SATFD: voir'), ('Medecin_voir_inactif', 'SATFD: voir inactif'), ('Medecin_voir_details', 'SATFD: voir details'), ('Medecin_ajouter', 'SATFD: ajouter'), ('Medecin_modifier', 'SATFD: modifier'), ('Medecin_activer', 'SATFD: activer'), ('Medecin_desactiver', 'SATFD: desactiver'), ('Medecin_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.AddField(
            model_name='employe_mortuaire',
            name='morgue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.morgue'),
        ),
        migrations.AddField(
            model_name='employe_mortuaire',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employe',
            name='surcursale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.surcursale'),
        ),
        migrations.AddField(
            model_name='employe',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dmd_renfl_int',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('statut_demande', models.CharField(choices=[('En cours', 'En cours'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Visualisé', 'Visualisé')], max_length=50, null=True, verbose_name='Statut')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('employé', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.employe')),
                ('sucursale_cible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursale_cible', to='satfd.surcursale')),
                ('sucursale_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursale_source', to='satfd.surcursale')),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Dmd_renfl_int_voir', 'SATFD: voir'), ('Dmd_renfl_int_voir_inactif', 'SATFD: voir inactif'), ('Dmd_renfl_int_voir_details', 'SATFD: voir details'), ('Dmd_renfl_int_ajouter', 'SATFD: ajouter'), ('Dmd_renfl_int_modifier', 'SATFD: modifier'), ('Dmd_renfl_int_activer', 'SATFD: activer'), ('Dmd_renfl_int_desactiver', 'SATFD: desactiver'), ('Dmd_renfl_int_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Dmd_renfl_ext',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('statut_demande', models.CharField(choices=[('En cours', 'En cours'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Visualisé', 'Visualisé')], max_length=50, null=True, verbose_name='Statut')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('employé', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.employe')),
                ('source_monetaire_cible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.src_mone_ext')),
                ('sucursale_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.surcursale')),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Dmd_renfl_ext_voir', 'SATFD: voir'), ('Dmd_renfl_ext_voir_inactif', 'SATFD: voir inactif'), ('Dmd_renfl_ext_voir_details', 'SATFD: voir details'), ('Dmd_renfl_ext_ajouter', 'SATFD: ajouter'), ('Dmd_renfl_ext_modifier', 'SATFD: modifier'), ('Dmd_renfl_ext_activer', 'SATFD: activer'), ('Dmd_renfl_ext_desactiver', 'SATFD: desactiver'), ('Dmd_renfl_ext_supprimer', 'SATFD: supprimer')),
            },
        ),
        migrations.CreateModel(
            name='Consulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_created', models.DateField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('modified_by', models.CharField(max_length=500, null=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.medecin')),
                ('personne_inscrite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satfd.personne')),
            ],
            options={
                'ordering': ('date_created',),
                'permissions': (('Consulation_voir', 'SATFD: voir'), ('Consulation_voir_inactif', 'SATFD: voir inactif'), ('Consulation_voir_details', 'SATFD: voir details'), ('Consulation_ajouter', 'SATFD: ajouter'), ('Consulation_modifier', 'SATFD: modifier'), ('Consulation_activer', 'SATFD: activer'), ('Consulation_desactiver', 'SATFD: desactiver'), ('Consulation_supprimer', 'SATFD: supprimer')),
            },
        ),
    ]
