# Generated by Django 3.2.5 on 2022-07-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satfd', '0008_auto_20220703_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulation',
            new_name='Consultation',
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ('date_created',), 'permissions': (('Consultation_voir', 'SATFD: voir'), ('Consultation_voir_inactif', 'SATFD: voir inactif'), ('Consultation_voir_details', 'SATFD: voir details'), ('Consultation_ajouter', 'SATFD: ajouter'), ('Consultation_modifier', 'SATFD: modifier'), ('Consultation_activer', 'SATFD: activer'), ('Consultation_desactiver', 'SATFD: desactiver'), ('Consultation_supprimer', 'SATFD: supprimer'))},
        ),
    ]
